// In-process clipboard paste. All pasteboard and event work is serialized off the main actor; the
// delayed restore is deliberately decoupled from completion so the delivery FIFO can advance.

@preconcurrency import AppKit
@preconcurrency import CoreGraphics
import Foundation
import Security

enum ClipboardPaste {
    enum PasteStatus: Sendable {
        case pasteSubmitted, targetChanged, pasteNotPosted, pasteAmbiguous, error
    }

    static func paste(
        _ text: String,
        targetPid: Int?,
        completion: @escaping (PasteStatus) -> Void
    ) {
        Engine.shared.paste(text, targetPid: targetPid, completion: completion)
    }

    /// A clipboard marked by its owner as concealed (passwords) or transient (one-time codes), per the
    /// nspasteboard.org convention.
    static func isSensitive(_ snapshot: [[String: Data]]) -> Bool {
        snapshot.contains { item in
            item.keys.contains("org.nspasteboard.ConcealedType") || item.keys.contains("org.nspasteboard.TransientType")
        }
    }

    private final class Callback: @unchecked Sendable {
        let body: (PasteStatus) -> Void
        init(_ body: @escaping (PasteStatus) -> Void) { self.body = body }
    }

    private final class PendingRestore: @unchecked Sendable {
        let savedOriginal: [[String: Data]]
        let changeCount: Int
        let token: String
        var workItem: DispatchWorkItem?

        init(savedOriginal: [[String: Data]], changeCount: Int, token: String) {
            self.savedOriginal = savedOriginal
            self.changeCount = changeCount
            self.token = token
        }
    }

    private final class Engine: @unchecked Sendable {
        static let shared = Engine()

        private let queue = DispatchQueue(label: "com.sageathor.rhemion.app.clipboard-paste")
        private let sentinelType = NSPasteboard.PasteboardType("com.sageathor.rhemion.paste")
        private let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        private let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        private var pending: PendingRestore?

        func paste(
            _ text: String,
            targetPid: Int?,
            completion: @escaping (PasteStatus) -> Void
        ) {
            let callback = Callback(completion)
            queue.async { self.begin(text, targetPid: targetPid, callback: callback) }
        }

        private func begin(_ text: String, targetPid: Int?, callback: Callback) {
            guard !text.isEmpty else { callback.body(.pasteNotPosted); return }
            guard targetMatches(targetPid) else { callback.body(.targetChanged); return }
            guard let source = CGEventSource(stateID: .privateState) else {
                callback.body(.pasteNotPosted); return
            }

            // If a prior restore is pending and its tagged write is intact, its saved snapshot is the
            // real original clipboard. Carry that snapshot through instead of snapshotting our text.
            let savedOriginal: [[String: Data]]
            if let pending, stillOwns(changeCount: pending.changeCount, token: pending.token) {
                savedOriginal = pending.savedOriginal
                pending.workItem?.cancel()
                self.pending = nil
            } else {
                pending?.workItem?.cancel()
                pending = nil
                let t0 = DispatchTime.now().uptimeNanoseconds
                savedOriginal = snapshot()
                let snapMS = (DispatchTime.now().uptimeNanoseconds - t0) / 1_000_000
                // The snapshot sits on the paste path; a big clipboard (images) shows up here.
                if snapMS >= 20 { log("paste: clipboard snapshot took \(snapMS) ms (\(savedOriginal.count) item(s))") }
            }

            let (changeCount, token) = writeTagged(text)
            let state = CompletionState(callback: callback)

            let watchdog = DispatchWorkItem { [weak self, state] in
                guard let self, !state.completed else { return }
                if self.stillOwns(changeCount: changeCount, token: token) {
                    self.restore(savedOriginal)
                }
                self.complete(state, state.posted ? .pasteAmbiguous : .error)
            }
            state.watchdog = watchdog
            queue.asyncAfter(deadline: .now() + .milliseconds(1_500), execute: watchdog)

            queue.asyncAfter(deadline: .now() + .milliseconds(100)) { [weak self, state] in
                guard let self, !state.completed else { return }
                guard self.targetMatches(targetPid) else {
                    self.restoreIfOwned(savedOriginal, changeCount: changeCount, token: token)
                    self.complete(state, .targetChanged)
                    return
                }
                guard !self.modifiersHeld() else {
                    self.restoreIfOwned(savedOriginal, changeCount: changeCount, token: token)
                    self.complete(state, .pasteNotPosted)
                    return
                }

                // Construct all events before posting any, avoiding a half-built shortcut with a
                // stuck Command key. 0x37 is left Command; 0x09 is V.
                guard let cmdDown = CGEvent(keyboardEventSource: source, virtualKey: 0x37, keyDown: true),
                      let vDown = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: true),
                      let vUp = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: false),
                      let cmdUp = CGEvent(keyboardEventSource: source, virtualKey: 0x37, keyDown: false) else {
                    self.restoreIfOwned(savedOriginal, changeCount: changeCount, token: token)
                    self.complete(state, .pasteNotPosted)
                    return
                }
                cmdDown.flags = .maskCommand
                vDown.flags = .maskCommand
                vUp.flags = .maskCommand

                // Last check before ⌘V: if the user copied something in the last 100 ms, the clipboard is
                // theirs now. Pasting would insert THEIR content, so do not post, and leave it alone.
                guard self.stillOwns(changeCount: changeCount, token: token) else {
                    self.complete(state, .pasteNotPosted)
                    return
                }

                state.posted = true
                cmdDown.post(tap: .cghidEventTap)
                usleep(10_000)
                vDown.post(tap: .cghidEventTap)
                usleep(10_000)
                vUp.post(tap: .cghidEventTap)
                usleep(10_000)
                cmdUp.post(tap: .cghidEventTap)

                self.scheduleRestore(savedOriginal, changeCount: changeCount, token: token)
                self.complete(state, .pasteSubmitted)
            }
        }

        private final class CompletionState: @unchecked Sendable {
            let callback: Callback
            var completed = false
            var posted = false
            var watchdog: DispatchWorkItem?
            init(callback: Callback) { self.callback = callback }
        }

        private func complete(_ state: CompletionState, _ status: PasteStatus) {
            guard !state.completed else { return }
            state.completed = true
            state.watchdog?.cancel()
            state.watchdog = nil
            state.callback.body(status)
        }

        private func scheduleRestore(
            _ savedOriginal: [[String: Data]], changeCount: Int, token: String
        ) {
            let record = PendingRestore(
                savedOriginal: savedOriginal, changeCount: changeCount, token: token
            )
            pending = record
            let work = DispatchWorkItem { [weak self, weak record] in
                guard let self, let record, self.pending === record else { return }
                self.pending = nil
                self.restoreIfOwned(
                    record.savedOriginal, changeCount: record.changeCount, token: record.token
                )
            }
            record.workItem = work
            queue.asyncAfter(deadline: .now() + .milliseconds(250), execute: work)
        }

        private func snapshot() -> [[String: Data]] {
            (NSPasteboard.general.pasteboardItems ?? []).map { item in
                var entries: [String: Data] = [:]
                for type in item.types {
                    if let data = item.data(forType: type) { entries[type.rawValue] = data }
                }
                return entries
            }
        }

        private func restore(_ snapshot: [[String: Data]]) {
            let pasteboard = NSPasteboard.general
            pasteboard.clearContents()
            // A password manager's concealed/transient copy is not put back: it clears its own copy on a
            // timer by watching changeCount, which our paste already moved, so a restored secret would stay.
            guard !ClipboardPaste.isSensitive(snapshot) else { return }
            let items = snapshot.map { entries in
                let item = NSPasteboardItem()
                for (rawType, data) in entries {
                    item.setData(data, forType: NSPasteboard.PasteboardType(rawType))
                }
                return item
            }
            if !items.isEmpty { pasteboard.writeObjects(items) }
        }

        private func randomToken() -> String {
            var bytes = [UInt8](repeating: 0, count: 16)
            if SecRandomCopyBytes(kSecRandomDefault, bytes.count, &bytes) != errSecSuccess {
                arc4random_buf(&bytes, bytes.count)
            }
            return bytes.map { String(format: "%02x", $0) }.joined()
        }

        private func writeTagged(_ text: String) -> (Int, String) {
            let pasteboard = NSPasteboard.general
            let token = randomToken()
            pasteboard.clearContents()
            let item = NSPasteboardItem()
            item.setString(text, forType: .string)
            item.setData(Data(token.utf8), forType: sentinelType)
            item.setData(Data("1".utf8), forType: concealedType)
            item.setData(Data("1".utf8), forType: transientType)
            item.setData(Data("1".utf8), forType: autoGeneratedType)
            pasteboard.writeObjects([item])
            return (pasteboard.changeCount, token)
        }

        private func stillOwns(changeCount: Int, token: String) -> Bool {
            let pasteboard = NSPasteboard.general
            guard pasteboard.changeCount == changeCount,
                  let top = pasteboard.pasteboardItems?.first,
                  let data = top.data(forType: sentinelType),
                  String(data: data, encoding: .utf8) == token else { return false }
            return true
        }

        private func restoreIfOwned(
            _ snapshot: [[String: Data]], changeCount: Int, token: String
        ) {
            if stillOwns(changeCount: changeCount, token: token) { restore(snapshot) }
        }

        private func targetMatches(_ targetPid: Int?) -> Bool {
            guard let targetPid else { return true }
            guard let frontmost = NSWorkspace.shared.frontmostApplication else { return false }
            return Int(frontmost.processIdentifier) == targetPid
        }

        private func modifiersHeld() -> Bool {
            let relevant: CGEventFlags = [.maskCommand, .maskControl, .maskAlternate, .maskShift]
            return !CGEventSource.flagsState(.combinedSessionState).intersection(relevant).isEmpty
        }
    }
}
